### ISSUE TITLE
Add a button to run or copy in editor code from learn section

### ISSUE THREAD

**Issue by jbdoderlein** [GroupeMINASTE/OCaml#10]
**Is your feature request related to a problem? Please describe.**
See the result or play with the pieces of code in learn section is cool to see how the code work.

**Describe the solution you'd like**
A small button or some force touch action to copy/run code

**Comment by NathanFallet** [comment]
Currently the code can be copied by long pressing it, selecting all the code, and clicking on Copy.
I will add an interaction on the view to copy it with a simple click on the code.

**Comment by NathanFallet** [comment]
Reopening because should be supported in the new SwiftUI views (see #14)

**Comment by NathanFallet** [comment]
The documentation is now available online, code can be copied from the website.
