### ISSUE TITLE
Build the Android app

### ISSUE THREAD

**Issue by NathanFallet** [GroupeMINASTE/OCaml#22]
Checklist:
- [x] Open files in the editor
- [x] Save files
- [ ] Highlight code (see https://github.com/markusressel/KodeHighlighter/issues/18)
- [x] Execute code and show output in a console
- [x] Make this console interactive (input field)
- [x] Settings
- [x] Add analytics using DigiAnalytics (need to create a gradle package for that)

Partially done in #23

**Comment by cab404** [comment]
Is that your app? https://play.google.com/store/apps/details?id=me.nathanfallet.ocaml&hl=en_US&gl=US?

**Comment by NathanFallet** [comment]
> Is that your app? https://play.google.com/store/apps/details?id=me.nathanfallet.ocaml&hl=en_US&gl=US?

@cab404 Yes it is, it's a beta version available freely to be tested
